---
# Concourse pipeline: cf-resource-image
#   $ fly -t target sp -p cf-resource-image -c concourse.yml -l fly-vars.yml -l ~/sec/credentials-prod.yml
resources:
- name: src-git
  type: git
  source:
    uri: https://github.com/wdstar/cf-resource-image
    branch: master
- name: base-image
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: latest
    registry_mirror: https://((registry-mirror-domain))
      # e.g. https://registry.docker.example.com:5000
    ca_certs:
    - domain: ((registry-mirror-domain))
      # e.g. registry.docker.example.com:5000
      cert: ((docker-reg-ca-cert))
  check_every: 1h
- name: docker-reg
  type: docker-image
  source:
    repository: ((docker-id))/((name))
    #tag: latest
    username: ((docker-id))
    password: ((docker-pw))
  check_every: 12h

jobs:
- name: build-img
  plan:
  - aggregate:
    - get: src-git
      params:
        depth: 5
      trigger: false
    - get: base-image
      #params:
      #  skip_download: true
      trigger: true
  - task: put-cf-ver
    image: base-image
    config:
      platform: linux
      outputs:
      - name: cf-on-image
      run:
        path: sh
        args:
        - -c
        - |
          cf -v | awk '{ print $3 }' | awk -F+ '{ print $1 }' > cf-on-image/ver
          cat cf-on-image/ver
  - put: docker-reg
    params:
      build: src-git
      tag: cf-on-image/ver
      tag_as_latest: true
    get_params:
      skip_download: true
- name: test-img
  plan:
  - get: docker-reg
    trigger: true
  - task: echo-cf-ver
    image: docker-reg
    config:
      platform: linux
      run:
        path: sh
        args:
        - -c
        - |
          cf -v
